# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and Testing

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_deploy:
    runs-on: ubuntu-latest

    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Check if composer.json exists
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: 'composer.json'

      - name: Run composer install if composer.json exists
        if: steps.check_files.outputs.files_exists == 'true'
        run: composer validate --no-check-publish && composer install --prefer-dist --no-progress

      - name: Create .env file
        run: |
          echo "app.baseURL='https://api-event-kampus.azurewebsites.net/'" > .env
          echo "CI_ENVIRONMENT = production" >> .env
          echo "database.default.hostname = ${{ secrets.DB_HOST }}" >> .env
          echo "database.default.database = ${{ secrets.DB_NAME }}" >> .env
          echo "database.default.username = ${{ secrets.DB_USER }}" >> .env
          echo "database.default.password = ${{ secrets.DB_PASS }}" >> .env
          echo "database.tests.hostname = ${{ secrets.DB_HOST }}" >> .env
          echo "database.tests.database = ${{ secrets.DB_TEST_NAME }}" >> .env
          echo "database.tests.username = ${{ secrets.DB_USER }}" >> .env
          echo "database.tests.password = ${{ secrets.DB_PASS }}" >> .env 
          echo "authjwt.keys.default.0.secret = ${{ secrets.JWT_SECRET }}" >> .
      
      - name: Run Migration
        run: |
          php spark migrate

      - name: Run Tests
        run: |
          composer test

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'api-event-kampus'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .
